# Whether or not to enable invisible slimes for easily seeing invisible item frames
slimes-enabled: false

# Whether or not to enable invisible item frames glowing when there's no item in them
# This will also make them visible when there's no item in them
item-frames-glow: true

# The item in the center of the recipe
# Recommended to use "/iframe setitem" to change this
recipe:
  ==: org.bukkit.inventory.ItemStack
  v: 2567
  type: LINGERING_POTION
  meta:
    ==: ItemMeta
    meta-type: POTION
    potion-type: minecraft:invisibility